### ISSUE TITLE
Slash /neav command to move stuff around not working

### ISSUE THREAD

**Issue by Astug** [lithammer/NeavUI#300] opened 2020-10-27 09:28 UTC
17x ...ddOns\oUF_Neav\modules\oUF_MovableFrames\movable.lua:470: attempt to call method 'SetBackdrop' (a nil value)
[string "@oUF_Neav\modules\oUF_MovableFrames\movable.lua"]:470: in function <...ddOns\oUF_Neav\modules\oUF_MovableFrames\movable.lua:461>
[string "@oUF_Neav\modules\oUF_MovableFrames\movable.lua"]:1012: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5073: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4737: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4773: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
obj = oUF_Neav_Player {
 ReadyCheckIndicator = oUF_Neav_PlayerReadyCheckIcon {
 }
 HONOR_LEVEL_UPDATE = <function> defined @oUF\elements\pvpindicator.lua:109
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @oUF\elements\castbar.lua:102
 unitEvents = <table> {
 }
 PhaseIndicator = oUF_Neav_PlayerPhaseIcon {
 }
 UNIT_MAXHEALTH = <table> {
 }
 PLAYER_UPDATE_RESTING = <table> {
 }
 UNIT_POWER_FREQUENT = <function> defined @oUF\elements\power.lua:249
 UNIT_LEVEL = <function> defined @oUF_Neav\core.lua:396
 PowerPrediction = <table> {
 }
 UPDATE_SHAPESHIFT_FORM = <function> defined @oUF_Neav\core.lua:396
 UNIT_POWER_BAR_SHOW = <function> defined @oUF\elements\power.lua:249
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @oUF\elements\castbar.lua:290
 PLAYER_REGEN_DISABLED = <table> {
 }
 PLAYER_TOTEM_UPDATE = <function> defined @oUF_Neav\core.lua:396
 style = "oUF_Neav"
 PvPIndicator = oUF_Neav_PlayerPvPIcon {
 }
 ACTIVE_TALENT_GROUP_CHANGED = <function> defined @oUF_Neav\modules\oUF_LootSpecIndicator\lootspecindicator.lua:75
 UNIT_EXITED_VEHICLE = <table> {
 }
 MainPowerPrediction = oUF_Neav_PlayerPowerPowerPrediction {
 }
 UNIT_CONNECTION = <function> defined @oUF\elements\portrait.lua:87
 UNIT_HEAL_PREDICTION = <function> defined @oUF\elements\healthprediction.lua:197
 PLAYER_LOGIN = <function> defined @oUF_Neav\modules\oUF_LootSpecIndicator\lootspecindicator.lua:75
 statusSign = -1
 unit = "player"
 UNIT_SPELLCAST_DELAYED = <function> defined @oUF\elements\castbar.lua:184
 StatusFlash = oUF_Neav_PlayerStatusFlash {
 }
 UNIT_SPELLCAST_STOP = <table> {
 }
 UNIT_AURA = <function> defined @oUF_Neav\modules\portraittimers.lua:110
 LootSpecIndicator = oUF_Neav_PlayerSpecIcon {
 }
 IsTargetFrame = false
 UNIT_ENTERING_VEHICLE = <function> defined @oUF_Neav\core.lua:396
 Name = oUF_Neav_PlayerName {
 }
 UNIT_PORTRAIT_UPDATE = <function> defined @oUF\elements\portrait.lua:87
 HealthPrediction = <table> {
 }
 __tags = <table> {
 }
 UNIT_ENTERED_VEHICLE = <table> {
 }
 UNIT_POWER_BAR_HIDE = <function> defined @oUF\elements\power.lua:249
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @oUF\elements\castbar.lua:290
 UNIT_MAXPOWER = <function> defined @oUF\elements\power.lua:249
 UNIT_TARGET = <function> defined @oUF_Neav\modules\smartthreat.lua:41
 CINEMATIC_STOP = <function> defined @oUF_Neav\core.lua:396
 PvPTimer = oUF_Neav_PlayerPvPTimer {
 }
 GroupRoleIndicator = oUF_Neav_PlayerGroupRoleIcon {
 }
 Texture = oUF_Neav_PlayerFrameTexture {
 }
 UNIT_SPELLCAST_SUCCEEDED = <function> defined @oUF\elements\powerprediction.lua:129
 PARTY_MEMBER_ENABLE = <function> defined @oUF_Neav\modules\offline.lua:18
 PARTY_LEADER_CHANGED = <function> defined @oUF\elements\leaderindicator.lua:59
 Power = oUF_Neav_PlayerPower {
 }
 UNIT_HEAL_ABSORB_AMOUNT_CHANGED = <function> defined @oUF\elements\healthprediction.lua:197
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @oUF_Neav\core.lua:396
 PLAYER_LOOT_SPEC_UPDATED = <function> defined @oUF_Neav\modules\oUF_LootSpecIndicator\lootspecindicator.lua:75
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @oUF_Neav\modules\smartthreat.lua:41
 UNIT_PHASE = <function> defined @oUF\elements\phaseindicator.lua:102
 UNIT_HEALTH = <table> {
 }
 Health = oUF_Neav_PlayerHealth {
 }
 RAID_TARGET_UPDATE = <function> defined @oUF\elements\raidtargetindicator.lua:62
 PORTRAITS_UPDATED = <function> defined @oUF\elements\portrait.lua:87
 UNIT_MODEL_CHANGED = <function> defined @oUF\elements\portrait.lua:87
 NotHere = oUF_Neav_PlayerNotHere {
 }
 UNIT_FACTION = <functio

**Comment by lithammer** [comment] 2020-10-27 09:33
This is a duplicate of https://github.com/lithammer/NeavUI/issues/296 which has already been fixed. Unfortunately I haven't uploaded a release on WoWI including the fix yet.

Depending on how handy you are, you can apply the fix manually. But my plan is to upload a new release today-ish.

```diff
diff --git a/Interface/AddOns/oUF_Neav/modules/oUF_MovableFrames/movable.lua b/Interface/AddOns/oUF_Neav/modules/oUF_MovableFrames/movable.lua
index 1d2475ca..99efdc74 100644
--- a/Interface/AddOns/oUF_Neav/modules/oUF_MovableFrames/movable.lua
+++ b/Interface/AddOns/oUF_Neav/modules/oUF_MovableFrames/movable.lua
@@ -463,7 +463,7 @@ do
 		if(not target:GetCenter()) then return end
 		if(backdropPool[target]) then return backdropPool[target] end
 
-		local backdrop = CreateFrame"Frame"
+		local backdrop = CreateFrame("Frame", nil, UIParent, "BackdropTemplate")
 		backdrop:SetParent(UIParent)
 		backdrop:Hide()
 ```

**Closed by lithammer** 2020-10-27 09:33 UTC
Labels: bug
